services:
    app.email_manager.order_notification:
        public: true
        class: App\EmailManager\OrderNotificationEmailManager
        arguments:
            - '@sylius.email_sender'
            - '@sylius.context.channel'
