services:
    app.menu.supplier_menu_builder:
        class: App\Menu\SupplierMenuBuilder
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: buildMenu }
