imports:
    - { resource: "@SyliusCoreBundle/Resources/config/app/config.yml" }

    - { resource: "@SyliusAdminBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusAdminApiBundle/Resources/config/app/config.yml" }

    - { resource: "@SyliusShopBundle/Resources/config/app/config.yml" }

parameters:
    sylius_core.public_dir: '%kernel.project_dir%/public'

sylius_product:
    resources:
        product:
            classes:
                model: App\Entity\Product
                interface: App\Entity\ProductInterface
                    
sylius_resource:
    drivers:
        - doctrine/orm
    resources:
        app.supplier:
            driver: doctrine/orm # You can use also different driver here
            classes:
                model: App\Entity\Supplier
                interface: App\Entity\SupplierInterface
                form: App\Form\Type\SupplierType

sylius_grid:
    grids:
        app_admin_supplier:
            driver:
                name: doctrine/orm
                options:
                    class: App\Entity\Supplier
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                description:
                    type: string
                    label: sylius.ui.description
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                        
sylius_shop:
    product_grid:
        include_all_descendants: true

sylius_theme:
    sources:
        filesystem:
            scan_depth: 1
            directories:
                - "%kernel.project_dir%/themes"

sylius_mailer:
    emails:
        order_notification:
            subject: app.ui.new_order
            template: 'App/Admin/Email/orderNotification.html.twig'
